name: Bazel CI

on:
  push:
    branches: [ "master","relaese/*","develop/*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Bazel Action
      uses: ngalaiko/bazel-action@2.0.0
      with:
        # Arguments to the bazel command
        args: run //src:demo
